name: fasal
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  lottie: ^3.3.1
  url_launcher: ^6.3.1
  html: ^0.15.5
  fl_chart: ^0.70.2
  intl: ^0.19.0
  translator: ^1.0.3+1
  flutter_markdown: ^0.7.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true # Moved here for localization generation

  # Uncomment and add assets if needed:
  assets:
    - lib/l10n/app_en.arb
    - lib/l10n/app_hi.arb
    - assets/logo.png
    # - lib/l10n/app_mr.arb
    # - lib/l10n/app_pa.arb

  # Uncomment and add fonts if needed:
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic